### ISSUE TITLE
GxAmplifier-x automatable bypass

### ISSUE THREAD

**Issue by cyrusadkisson** [brummer10/GxPlugins.lv2#11]
Sorry to post this here as I know GxAmplifier plugin resides in the main Guitarix package, but I know you check these issues and I'd rather not take a trip back in time to Sourceforge, if I can help it. (I already posted to /r/guitarix.)

Anyway, I'm desperate for an automatable bypass on GxAmplifier. Most of the songs I play have a clean and dirty toggle (90s alt, baby! yeah!) and without a toggle on GxAmplifier, I have to do some undesirable workarounds. I can either:

1. Set GxAmplifier to clean and use pedals for dirt.
2. Automate all the different knobs back and forth each time. 

With #1, I lose all the nice authentic dirty tone versatility of GxAmplifier and add CPU cycles.
With #2, it's messy, labor intensive and prone to error. 

If GxAmplifier were bypassable, I could have two instances and then just switch back and forth with the settings all precisely set in stone and non-automated.

What do you think?

(I looked through the code and found some of the bypass portions, but really couldn't make heads or tails of it. I'm a Java guy... womp.)

**Comment by cyrusadkisson** [comment]
Alternatively, I could use an a/b switcher, but I can't find one in my Ardour plugins. Do you know of a package that has one?

**Comment by brummer10** [comment]
Hi

Yes, I'll add the bypass function to all guitarix LV2 plugins during the move the X11 based UI's. But, as I said on reddit, I couldn't manage it this year. 

regards
hermann
