### ISSUE TITLE
Lots of popping on GxBottleRocket

### ISSUE THREAD

**Issue by cyrusadkisson** [brummer10/GxPlugins.lv2#16]
Bottle rocket is causing some popping when strumming medium-hard. My instrument-in audio interface shows no clipping. Other overdrives (GxSD1) don't pop at the same levels and strumming intensities.

Note that I was able to reproduce the popping on an EMG active high output set of pickups as well as some single coils. However, I couldn't reproduce with my very, very low output stratocaster. Clearly the issue has to do with the input signal strength. but it's popping earlier than it should be and is not handling clipping very well.

**Comment by brummer10** [comment]
Hi

Yea, the Bottlerocket was one of the first tube based pedal simulations I wrote, I'll replace it with a newer version to cover what I've learned in the mean time. 

regards
hermann

**Comment by cyrusadkisson** [comment]
Thanks. Welcome back.
