### ISSUE TITLE
Asset for v0.6 has mismatching file name

### ISSUE THREAD

**Issue by dvzrv** [brummer10/GxPlugins.lv2#19]
Hi! I'd like to move gxplugins to the Arch Linux [community] repositories.
I noticed, that the assets for v0.6 have a file name, that doesn't match with the version though (https://github.com/brummer10/GxPlugins.lv2/releases/download/v0.6/GxPlugins_06.tar.gz where it should be https://github.com/brummer10/GxPlugins.lv2/releases/download/v0.6/GxPlugins_0.6.tar.gz or better yet https://github.com/brummer10/GxPlugins.lv2/releases/download/v0.6/GxPlugins-0.6.tar.gz).

Maybe a script to automate the creation of the asset could help? If you're up for it, this could even include the creation of a detached PGP signature, that could be uploaded alongside it.

Would you be interested in a pull request for this?

**Comment by brummer10** [comment]
Hi

Ups, yes a pull request will be welcome. 

regards
hermann

**Comment by brummer10** [comment]
I've set up a script now to avoid such issues in the future. Still, the name of the archive will be remain lowercase. 
I'll push out a new release soon.

regards
hermann

**Comment by dvzrv** [comment]
@brummer10 I know you consider this closed, but I would like you to consider my pull request nonetheless.
It _reproducibly_ creates assets for this project from a tag and optionally enables you to easily create a detached gpg signature for your assets.
Additionally, it decreases the asset size by two thirds (22Mb instead of 67Mb) by removing unnecessary files (e.g. `.git` directories).

A bonus: The created asset decompresses to `GxPlugins_${version}`, so extracting different versions don't overwrite each other!
