### ISSUE TITLE
Makefile wildcard too inclusive

### ISSUE THREAD

**Issue by fps** [brummer10/GxPlugins.lv2#2]
<code>SUBDIR := $(wildcard *.lv2/)</code>

or alternatively

<code>SUBDIR := $(filter-out  debian/, $(SUBDIR))</code>

**Comment by brummer10** [comment]
This was added 17 days ago:
https://github.com/brummer10/GxPlugins.lv2/commit/01ce71fb69996975ab4d39d17bc56dfd7d05aad5

**Comment by fps** [comment]
Ooops, I was too hasty because I was short on time. I had another subdir made by <code>checkinstall</code>. This was picked up by the wildcard, too. So I guess the first one (whitelisting more exclusively) rather than the second one would be the way to go :) Thanks for your reply..

**Comment by brummer10** [comment]
Okay, even if I'm not a fan of checkinstall (I prefer dh_make) I understand the request.
I've pushed a change to git now.

**Comment by fps** [comment]
thanks :)
