### ISSUE TITLE
GxTubeDistortion.lv2/MOD/modgui.ttl missing?

### ISSUE THREAD

**Issue by falkTX** [brummer10/GxPlugins.lv2#26]
Is this file missing, or was the modgui never finished?
I just started updating the package I have for the new kxstudio repos, trying to make it install desktop + modgui, but my script fails with this modgui.ttl file being missing.
The modgui folder is there, so my guess is that you forgot to add and push it

**Comment by brummer10** [comment]
Hi
It's there, but I forgot to update the commit hash for the GxPlugins package.
Done now.

**Comment by falkTX** [comment]
Indeed. I see it now, thanks!
