### ISSUE TITLE
recursive use of port_event and write_function

### ISSUE THREAD

**Issue by falkTX** [brummer10/GxPlugins.lv2#27]
When a host calls the UI `port_event` on your plugins, you are right away calling `write_function` too.
`port_event` on your UI is for the host to tell you when something changed on the DSP side.
the `write_function` is for you to tell the host when a parameter has changed in the UI.
Right now it keeps going back and forth... it is nasty as it easily leads to recursion.

Please fix your gui code.
Thanks

**Comment by brummer10** [comment]
I remember that we've talked about this when the GxPlugs use the GTK UI's and I've implemented a guard to avoid this. Seem's I've forgotten to do so for the X11 UI's. 
Will check my old stuff and bring the guard back. 
Might take some time.
