### ISSUE TITLE
Monk and Terrors?

### ISSUE THREAD

**Issue by cyrusadkisson** [brummer10/GxPlugins.lv2#28]
Great work on this project. 

Curious if you'll be including the more recent plugins (Monk, Terror, etc) here? Or should I grab them separately?

**Comment by brummer10** [comment]
Hi Cyrus
The monks will definitely not been included in the GxPlugins pack, and the terrors properly as well not. It may be that I start a new pack for the new plugs, but it's not decided.
If you would try them out, best grab them directly from there repository's.

regards
hermann
