### ISSUE TITLE
Standard make (as user) make install (as root) not working

### ISSUE THREAD

**Issue by fps** [brummer10/GxPlugins.lv2#3]
Stuff gets rebuilt excessively.

**Comment by brummer10** [comment]
Please, be a bit more verbose with your issue reports. 
While, for the release, this is true, the readme for the release clearly state to run just make install. 
This has changed a bit in the current git. It's is work under progress, I changed a couple of plugs to build on the mod-plugin-builder with MOD UI, therefore I've changed the makefiles of them. Those plugs now need the good old make && make install stack. The other plugs which are currently not ported to the MOD, will follow, even if I don't add MOD UI's to them, they will recive a update in the makefiles. 
Then, we've anything in sync again. 
Anyway, thanks for your comments, nice to know that those plugs get some attention.
Hope you enjoy them. 

regards
hermann

**Comment by brummer10** [comment]
> The other plugs which are currently not ported to the MOD, will follow, even if I don't add MOD UI's to them, they will recive a update in the makefiles.
Then, we've anything in sync again.

Okay, I've updated all makefiles now, so no more rebuild on make install.

**Comment by Gimmeapill** [comment]
Thanks - that will indeed speed up packaging. I'll double check if the Arch pkgbuild needs an update in the next few days.
