### ISSUE TITLE
VMK2 vibe toggle doesn't work

### ISSUE THREAD

**Issue by cyrusadkisson** [brummer10/GxPlugins.lv2#30]
If you add vmk2 to a mixer strip in ardour and then use its gui to activate/deactivate the vibe, it'll sometimes work and sometimes fail. 

Here's a video of it in action. If you can't hear it, what's happening is:

1. I toggle the vibe on: OK
2. I toggle the vibe off: OK
3. I toggle the vibe on: doesn't work. No vibe is audible.

https://youtu.be/PG2lqP3NLyY

**Comment by brummer10** [comment]
I cant reproduce that. Here is what I get:
https://www.youtube.com/watch?v=NYKfMc5dWOQ

**Comment by cyrusadkisson** [comment]
Strange. I think my pull of GxPlugins.lv2 is pretty recent. Any late changes?

**Comment by brummer10** [comment]
No, not in the last month. 
Do you've this issue on a ARM device, or even on a x86 one?

**Comment by cyrusadkisson** [comment]
I'm seeing this behavior on my desktop machine. Stock ubuntu (gnome) 20.04 x64.

**Comment by brummer10** [comment]
hmm. 
I may rewrite this as well, as some things in there I would do today a bit different then it is now. 
I'll put it on my to-do list.

**Comment by brummer10** [comment]
I've pushed a update for GxVmk2 to GxPlugins.lv2. 
True, I don't know if that fix the issue for you, but may be possible.
