### ISSUE TITLE
Can't load GxPlugins in guitarix

### ISSUE THREAD

**Issue by davidebasilio** [brummer10/GxPlugins.lv2#32]
I cloned the GxPlugins.lv2 repo and installed it locally (with `make install`) into `~/.lv2`.
Now I expected to be able to use the new plugins from guitarix, but I don't see them in the plugin settings and I haven't found a way to change or configure the plugin search path.

Is guitarix supposed to pick up new plugins from `~/.lv2`?

Thanks.

**Comment by brummer10** [comment]
guitarix use lilv for plugin scanning, so yes, plugins installed in ~/.lv2 should be appear in the guitarix plugin browser. 
I've installed them as well in ~/.lv2 and use them in guitarix. 
I've no idea why the are not there for you. Are they available in other hosts?

**Comment by davidebasilio** [comment]
Mhh.. Maybe the issue is due to missing dependencies on my installation..
I tried to check one of the plugins with `lv2_validate` and I get some errors:
```
$ lv2_validate ~/.lv2/gx_blueamp.lv2/gx_blueamp.ttl 
Skipping file /usr/lib64/lv2/eg-amp.lv2/manifest.ttl
Skipping file /usr/lib64/lv2/eg-amp.lv2/amp.ttl
Skipping file /usr/lib64/lv2/eg-fifths.lv2/manifest.ttl
Skipping file /usr/lib64/lv2/eg-fifths.lv2/fifths.ttl
Skipping file /usr/lib64/lv2/eg-midigate.lv2/manifest.ttl
Skipping file /usr/lib64/lv2/eg-midigate.lv2/midigate.ttl
Skipping file /usr/lib64/lv2/eg-scope.lv2/manifest.ttl
Skipping file /usr/lib64/lv2/eg-scope.lv2/examploscope.ttl
Skipping file /usr/lib64/lv2/eg-sampler.lv2/manifest.ttl
Skipping file /usr/lib64/lv2/eg-sampler.lv2/sampler.ttl
Skipping file /usr/lib64/lv2/core.lv2/lv2core.doap.ttl
Skipping file /usr/lib64/lv2/eg-metro.lv2/manifest.ttl
Skipping file /usr/lib64/lv2/eg-metro.lv2/metro.ttl
Skipping file /usr/lib64/lv2/eg-params.lv2/manifest.ttl
Skipping file /usr/lib64/lv2/eg-params.lv2/params.ttl
error: Subject not in domain <http://usefulinc.com/ns/doap#Project>
       http://guitarix.sourceforge.net/plugins/gx_blueamp_#_blueamp_
       http://usefulinc.com/ns/doap#maintainer
       http://guitarix.sourceforge.net#me
error: Object not in range <http://lv2plug.in/ns/lv2core#ExtensionData>

       http://guitarix.sourceforge.net/plugins/gx_blueamp_gui#_blueamp_
       http://lv2plug.in/ns/lv2core#extensionData
       http://lv2plug.in/ns/extensions/ui#:idle
error: Object not in range <http://lv2plug.in/ns/lv2core#Feature>

       http://guitarix.sourceforge.net/plugins/gx_blueamp_gui#_blueamp_
       http://lv2plug.in/ns/lv2core#requiredFeature
       http://lv2plug.in/ns/extensions/ui#makeResident
Found 3 errors among 98 files (checked 1910 restrictions)
```

I guess the issue is indeed not with guitarix, then.
I have `lv2` version 1.18.2 installed., would you have an idea how I could get the missing plugins?
Thanks for your help!

**Comment by davidebasilio** [comment]
Never mind, I figured things out.
I had to set `LV2_PATH` to include `~/.lv2`.
Now the plugins do show up.
Hopefully the info can be useful for someone else in the future :-).
