### ISSUE TITLE
ON/OFF toggle button doesn't work on several plugins

### ISSUE THREAD

**Issue by trebmuh** [brummer10/GxPlugins.lv2#33]
Hi @brummer10 

with GxBottleRocket, GxDOP250, GxHotBox, GxSD1, GxSD2Lead, GxValveCaster, GxBoobTube, the ON/OGG button of the plugin's GUI doesn't work as expected in Ardour.
[In this video](https://exode.me/videos/watch/71fe16f9-c191-4ba4-b7cf-3dff1cd2f5fe) is an example of what's happening.

The plugin's GUI ON/OFF button seems to work as expected only once, then we have to use the ardour bypass button after that.

Note that I've been trying those right now with the Gx-Plugins from GIT master and Ardour 6.6

_Edit: please, note that it works as expected in Qtractor 0.9.17_

**Comment by brummer10** [comment]
Hi @trebmuh 
Strange, works here in Ardour 6.5 as well as expected. 
Seems we need to ask @x42 what Ardour have changed for bypass handling.

**Comment by x42** [comment]
I'm using guitarix-lv2 from debian (v0.42.1) so I do not have any of the plugins mentioned above. The ones I have access to work correctly. I cannot reproduce the issue.

I don't have an explanation why this would be. There have not been any changes to bypass/enable, nor any LV2 related changes in a while.

- Could it be that you may have automated the bypass/enable?
- Does it work when you start a clean, new session?

**Comment by trebmuh** [comment]
> Could it be that you may have automated the bypass/enable?

No.

> Does it work when you start a clean, new session?

The same behavior happens (ie: the GUI bypass button doesn't work as expected).

**Comment by brummer10** [comment]
@trebmuh 
Is there on of the plugs from the GxPlugins where the bypass work as expected or been all infected?
Also, the ones from the guitarix package, did they work or been they infected as well?

**Comment by x42** [comment]
The problem is that ui->block_event does not get reset.

1. toggle button in the GUI  `switch_event()` -> `check_value_changed()`
2. Plugin asks Ardour to change value to 1 -> 0 and then sets `ui->block_event = -1;`
3. Ardour informs Plugin that the value has indeed been changed (no automation), and calls port-event
4. GX `port_event()` sets `ui->block_event = (int)port_index;` and calls `check_value_changed()`
5. `check_value_changed()` does not detect a change and returns early
6. ui->block_event is never reset to -1.
 

```diff
diff --git a/GxBottleRocket.lv2/gui/gx_bottlerocket_x11ui.c b/GxBottleRocket.lv2/gui/gx_bottlerocket_x11ui.c
index 31f4fb8..5bdc7f4 100644
--- a/GxBottleRocket.lv2/gui/gx_bottlerocket_x11ui.c
+++ b/GxBottleRocket.lv2/gui/gx_bottlerocket_x11ui.c
@@ -589,6 +589,7 @@ static void port_event(LV2UI_Handle handle, uint32_t port_index,
 		if (port_index == ui->controls[i].port) {
 			ui->block_event = (int)port_index;
 			check_value_changed(ui, i, &value);
+			ui->block_event = -1;
 		}
 	}
 }
```

**Comment by trebmuh** [comment]
Confirmed that this latest fix on GIT master makes them work as expected now.
Thanks @x42 and @brummer10
