### ISSUE TITLE
Release page links tarball with no submodules

### ISSUE THREAD

**Issue by yurivict** [brummer10/GxPlugins.lv2#34]
The tarball under "Assets" https://github.com/brummer10/GxPlugins.lv2/archive/refs/tags/v0.9.tar.gz has no submodules.

The other tarball above the "Assets" section https://github.com/brummer10/GxPlugins.lv2/files/6329721/GxPlugins_0.9.tar.gz does have submodules.

In your case a tarball without submodules is useless.

**Comment by brummer10** [comment]
@yurivict 
That's exactly what is mentioned in the release notes. The tarball provided by github is useless as it didn't contain the submodules nor the git instructions to download them. This is a well known issue on github for several years now and I've no idea how to avoid that. Those tarballs been created by github as soon you push a tag to the repository and there is no way to remove them. Hence the note on the release page.

>The Source code files below contain only the empty submodules, don't use them, use GxPlugins_0.9.tar.gz

**Comment by yurivict** [comment]
I see, thanks!
