### ISSUE TITLE
Tarball for 0.9 served at unpredictable URL

### ISSUE THREAD

**Issue by dvzrv** [brummer10/GxPlugins.lv2#35]
Hi! The release for 0.9 serves the tarball with all the included assets at a URL that is unpredictable.

Compare with 0.8 release:

https://github.com/brummer10/GxPlugins.lv2/files/6329721/GxPlugins_0.9.tar.gz
https://github.com/brummer10/GxPlugins.lv2/releases/download/v0.8/GxPlugins_0.8.tar.gz

This is because the file is included in the description of the release, not as a release asset.
This makes it more cumbersome to package, because packagers now have to go to the release page and find out the unique number for each release (e.g. `6329721`).
It would be highly appreciated if you could upload the tarball as an asset again, so that it ends up in a predictable location.

**Comment by brummer10** [comment]
Ah, yea, I dropped it in the wrong area. I've pushed it to asset now as well.

regards
hermann

**Comment by dvzrv** [comment]
Thanks a lot! :)
