### ISSUE TITLE
Implementing support for compilation on MSWin

### ISSUE THREAD

**Issue by torte71** [brummer10/GxPlugins.lv2#40]
Hi @brummer10 
To compile these plugins for MSWin, the linker flags in all Makefiles of each subproject need to be changed.
I could fork all subprojects, apply the changes and then open pull requests for each of them.
But there is also the option to provide just a single build script (in this main project), that runs sed on all Makefiles to replace the undesired flags with the wanted ones, (once,) just before compiling.
That's hackish, but saves a lot of effort and makes it really easy to see, what changes are actually made.
Which way would you prefer?

**Comment by brummer10** [comment]
Hi @torte71 
A single build script for GxPlugins sounds good to me. It's indeed a nice way for me to see what's needed to change. 
I could then later push the needed changes from GxPlugins to the single repository's. That will be needed (sooner or later) to keep stuff in sync.
