### ISSUE TITLE
GxVBassPreAmp lv2

### ISSUE THREAD

**Issue by dsreyes1014** [brummer10/GxPlugins.lv2#5]
Trying to use this at 96k and it just loops and gives me feedback.  This is on Ardour and Carla.  When I bypass the plugin it doesn't loop.

**Comment by brummer10** [comment]
Hi
Well, this filter becomes unstable at 96kHz. 
Unfortunately there is no way to stabilize it on higher sample rates, without change the filter characteristics.  
To avoid this issue I've added a resampler now, and downsample internal to 48kHz, when needed. 

regards
hermann
