### ISSUE TITLE
Add the possibility to set globally INSTALL_DIR

### ISSUE THREAD

**Issue by ycollet** [brummer10/GxPlugins.lv2#6]
Add the possibility to set globally INSTALL_DIR.
Currently, INSTALL_DIR is set to: INSTALL_DIR = /usr/lib/lv2
On Fedora / Red Hat, the INSTALL_DIR should be set to: INSTALL_DIR = /usr/lib64/lv2

What about adding:
```
INSTALL_DIR ?= /usr/lib/lv2
```
In each Makefile ?

**Comment by brummer10** [comment]
Hi ycollet

You could simply overwrite the INSTALL_DIR variable, there is no need for the `?` to do so.
Just try 
`make install INSTALL_DIR='/usr/lib64/lv2'`
