### ISSUE TITLE
Please don't put .h files into build lines

### ISSUE THREAD

**Issue by yurivict** [brummer10/GxPlugins.lv2#7]
clang fails to create shared libs in such case for some reason.

**Comment by brummer10** [comment]
Sure, I could remove them, just it is easier for me to force a re-build when I've worked on the header files.

**Comment by yurivict** [comment]
> Sure, I could remove them, just it is easier for me to force a re-build when I've worked on the header files.

You should list .h files separately, and make object files depend on them, this will force a rebuild.

**Comment by brummer10** [comment]
Okay, done.

Thanks for your reports and your patience.

**Comment by yurivict** [comment]
Thank you!
