### ISSUE TITLE
Build fails on FreeBSD 12

### ISSUE THREAD

**Issue by yurivict** [brummer10/GxPlugins.lv2#9]
```
ld: error: target emulation unknown: -m or at least one .o file required
gmake[2]: [Makefile:75: gui/pedal.o] Error 1 (ignored)
ld: error: target emulation unknown: -m or at least one .o file required
gmake[2]: [Makefile:76: gui/pedal.o] Error 1 (ignored)
```

Here is a complete log: http://beefy12.nyi.freebsd.org/data/head-amd64-default/p482319_s339416/logs/gxplugins-lv2-0.5.log

It looks like it doesn't build anything at all on FreeBSD 12.
It builds fine on FreeBSD 11 and 10.

**Comment by brummer10** [comment]
Hi Yuri

Seems like the generation of the object files from the png's fail on FreeBSD 12. 

Isn't the  ld GNU linker part of FreeBSD 12 any more?

**Comment by yurivict** [comment]
Hi,

What is the feature that is used from the GNU linker that is missing?

**Comment by brummer10** [comment]
we use the flags 
-r  Generate relocatable output
-b input-format (binary)

looks like the ELF linker from the LLVM	project need the flags 
--relocatable
--format=input-format (binary)
to do the same.

**Comment by yurivict** [comment]
Ok, thanks, I switched the port to use the GNU linker for now. Will see how this works.

**Comment by brummer10** [comment]
Hi Yuri

I see on your makefile
https://freshbsd.org/commit/freebsd-ports/r482631?view=head%2Faudio%2Fgxplugins-lv2%2FMakefile
that you still have gtk20 gdkpixbuf2 atk and  pango in the "use" list, they been ain't in use any more, this release is aimed to remove this dependency's.  

regards
hermann

**Comment by yurivict** [comment]
Thank you for pointing this out. I removed the redundant USExx elements.
But they wouldn't cause link breakage, they would only attach additional dependencies.
